### ISSUE TITLE
GUI and Feature Suggestions

### ISSUE THREAD

**Issue by ConstantDust** [tresabhi/stellar#2]
hi just a few things,

- I recently had the same idea with the sfs editor but id know lua and the very basics java if you want some help coding and ik my way around unity

- I have a few minor suggestions such as customizable  gui and possible making collections (a savable collection of parts such as a hinge or a piston etc.)

- if you do it it will be after the main blueprint editor is done but what if you made a editor for language and solar system packs as well id be cool to make your own editor

- also may I suggest if you cant get it onto iOS make a save file button so the blueprint.txt and version.txt can be transferred over manually

if you need any help at all or any ideas my discord is ConstantDust#9485

**Comment by CoolAbhi1290** [comment]
# Outline
- **Customisable GUI:** themes?
- **Collections**: snippets of a small collection of parts
- **Language editor**: _never_ coming to Stellar Editor
- **Planet editor**: it's planned already
- **iOS**: why not, I'm planning for that too

**Comment by ConstantDust** [comment]
#Outline 
for themes I have a few basic color pallets I use in scripting ide's such as a purple and blue space theme, a orange and black theme, light mode theme with cyan yellow and white, retro using very vibrant colors, you could also have a small editor that lets you make your own themes customizing parts of the editor such as a toolbar background text etc.

**Comment by CoolAbhi1290** [comment]
I have already planned, and partially implemented this featured (yesterday). You will be able to customize essentially all of the colors in the editor.

**Comment by TresAbhi** [comment]
Test message

**Comment by TresAbhi** [comment]
Okay, I'm about to implement this feature. I am planning to not have any officially supported themes (but this may change). I will implement a feature that will let 3<sup>rd</sup> party creators publish themes instead.

I'm close to being done!

**Comment by tresabhi** [comment]
Theming had been implemented. Working on implementating a way to switch between them.

**Comment by tresabhi** [comment]
This feature has been fully implemented in f2cdc25c51c77e3ea14b32c538fe44d6ba3a0cf5.
